{% set name = "Flask-Compress" %}
{% set version = "1.10.1" %}
{% set sha256 = "28352387efbbe772cfb307570019f81957a13ff718d994a9125fa705efb73680" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=2.7
    - pip
  run:
    - python >=2.7
    - flask
    - brotli-python

test:
  source_files:
    - tests
  imports:
    - flask_compress
  commands:
    - pip check
    - pytest tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/colour-science/flask-compress
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Compress responses in your Flask app with gzip.

  description: |
    Flask-Compress allows you to easily compress your Flask application's responses with gzip.
  dev_url: https://github.com/colour-science/flask-compress

extra:
  recipe-maintainers:
    - synapticarbors
    - mariusvniekerk
